### ISSUE TITLE
[Enhance] Please add queries that your program could do reasoning and suggestion.

### ISSUE THREAD

**Issue by veer66** [mickeycj/kem-rules#3]
Please add queries that your program could do reasoning and suggestion. Regarding to previous class. Since now the project is like relational database without inference engine.

**Comment by mickeycj** [comment]
I do understand that our project do behave like relational database. However, this is the scope of the project we have discussed with and is accepted by the professor, so I wonder if we should still enhance this aspect of the project or leave it as it is?

**Comment by veer66** [comment]
I discussed with Ajarn Asanee already. She asked to enhance it in order to make sure that everyone has enough knowledge and skill for the final exam.
